x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/root/.nanobot
  depends_on:
    - searxng
  environment:
    SEARXNG_BASE_URL: http://searxng:8080
    BW_CLIENTID: ${BW_CLIENTID:-}
    BW_CLIENTSECRET: ${BW_CLIENTSECRET:-}
    BW_PASSWORD_FILE: ${BW_PASSWORD_FILE:-}

services:
  searxng:
    container_name: nanobot-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./docker/searxng/settings.yml:/etc/searxng/settings.yml:ro
    depends_on:
      - searxng-redis

  searxng-redis:
    container_name: nanobot-searxng-redis
    image: docker.io/valkey/valkey:8-alpine
    restart: unless-stopped

  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
  
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
